### ISSUE TITLE
issue with User_data template

### ISSUE THREAD

**Issue by sudhakar470** [terraform-providers/terraform-provider-template#33]
Hi there,

### Terraform Version
0.9.8

### Affected Resource(s)
data "template_file"

### Terraform Configuration Files
provider "aws"{
    region="${var.aws_region}"
    access_key="${var.access_key}"
    secret_key="${var.secret_key}"
}
resource "aws_security_group" "default"{
    name="Sensu-sg"
    description="Created for sensu installation"
    vpc_id="vpc-3918dc5f"

    ingress{
        from_port = 22
        to_port = 22
        protocol= "tcp"
        cidr_blocks = ["10.0.0.0/8", "43.0.0.0/8","160.33.244.0/23","160.33.246.0/23"]
    }
    ingress{
        from_port = 2380
        to_port = 2380
        protocol= "tcp"
        cidr_blocks = ["10.0.0.0/8", "43.0.0.0/8"]
    }
    ingress{
        from_port = 3000
        to_port = 3000
                                                                                          1,1           Top
    ingress{
        from_port = 3000
        to_port = 3000
        protocol= "tcp"
        cidr_blocks = ["10.0.0.0/8", "43.0.0.0/8"]
    }
    ingress{
        from_port = 8080
        to_port = 8080
        protocol= "tcp"
        cidr_blocks = ["10.0.0.0/8", "43.0.0.0/8"]
    }
    ingress{
        from_port = 8081
        to_port = 8081
        protocol= "tcp"
        cidr_blocks = ["10.0.0.0/8", "43.0.0.0/8"]
    }
    ingress{
        from_port = 80
        to_port = 80
        protocol = "tcp"
        cidr_blocks = ["10.0.0.0/8", "43.0.0.0/8"]
    }
    egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

}

data "template_file" "init" {
  template = "${file("init.tpl")}"
}

resource "aws_instance" "Sensu_docker"{
    instance_type="m3.medium"
    ami="${lookup(var.aws_ami, var.aws_region)}"
    key_name = "sneelakantan"
     iam_instance_profile = "confluence_instance_role"
    security_groups = ["${aws_security_group.default.id}"]
    subnet_id = "${var.subnet_id}"
   user_data = "${data.template_file.init.rendered}"
   tags{
        Name="ec2-uw2-np-sensu-01"
    }
  }

### Expected Behavior
What should have happened?

user data we have mentioned to install amazon-ssm-agent and docker, using docker commands we are pulling some images and creating container , it is not taking user_data file.

### Actual Behavior
What actually happened?
instance getting created but user_data is not getting picked 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by apparentlymart** [comment]
Hi @sudhakar470! Sorry this didn't work as expected.

Since you mentioned that the EC2 instance is being created, that suggests that the `template_file` data source completed successfully here, so if there's an issue then it'd be one in [the AWS provider](https://github.com/terraform-providers/terraform-provider-aws) rather than in the template provider.

With that said, please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of [the community forums](https://www.terraform.io/community.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by the small set of maintainers of each repository.
